### ISSUE TITLE
Feature Request: Exceptions for injection: per site, per account

### ISSUE THREAD

**Issue by NukeManDan** [polkadot-js/extension#492] opened 2020-10-14 02:43 UTC
I am using https://ipfs.io/ipns/dotapps.io/ with the extention enabled in firefox.

On first use, I was prompted to allow injection ( didn't grab a screen cap, sorry), but after this I see no way to view what exceptions exist, for what sites, and for what accounts. 

I also had all accounts default to not interject *prior* to getting this prompt, and even after giving the OK for the site, I the app didn't detect the accounts until I unchecked the `visible` box.

So at the moment I see an **bug** as I don't have control or visibility of what injections I am allowing for what accounts, and now way to change them.

What I would love to see as a set of **features** is the direct ability to:
- Inject/not associated for each account for each page as a menu item sensitive to the domain I am interact with via the extension (similar to what metamask has presently :pray:)
- A global settings page with permissions per domain listed, and the ability to:
  - View all domains that can view injected accounts automatically
  - Select allowed accounts inject/not
  - Remove the domain completely
  - Add a new domain manually and select accounts to inject

**Comment by Tbaut** [comment] 2020-10-16 12:58
Thanks for the feedback

> On first use, I was prompted to allow injection ( didn't grab a screen cap, sorry), but after this I see no way to view what exceptions exist, for what sites, and for what accounts.

- For now there's no exception per domain, it's either you authorize all the visible accounts or none.
- Visibility for an account can be toggled on and off and #485 will make this better as right now you need to go to the menu to make an account invisible or not.

> I also had all accounts default to not interject prior to getting this prompt

Sure, we would not allow any injection if you haven't authorized it.

>  the app didn't detect the accounts until I unchecked the visible box.

This is the intended behavior, an invisible account should not be accessible by a Dapp.

Your feature request has been discussed in the past (but now you logged it so it's much better), and is definitely something we want to do. Not trivial to make it simple, but we should get there.

**Comment by jacogr** [comment] 2020-10-16 13:02
... "should get there" - eventually... 

Not in a rush to add this immediately since it adds a lot of complexity and it needs some much-needed cleanups internally first so it ends up solid.

**Comment by Tbaut** [comment] 2020-10-19 08:45
closing this one, since we already have #85

**Closed by Tbaut** 2020-10-19 08:45 UTC
Labels: <duplicate>
