### ISSUE TITLE
Help me, please. I can't log in to my account

### ISSUE THREAD

**Issue by Mazaltov888** [polkadot-js/extension#1415] opened 2024-07-25 17:18 UTC
Good afternoon. Help me, please. I can't log in to my account. Haven't used the account in a year. Now I downloaded the app in Chrome. Entered the keys, password. I click on the activate button, but it won't click. You can see from the screenshots. Thank you very much in advance for your respect
![WhatsApp Image 2024-07-25 at 15 28 35](https://github.com/user-attachments/assets/fd2d0137-cca0-4b05-b71a-88e12fc955eb)

![WhatsApp Image 2024-07-25 at 15 29 30](https://github.com/user-attachments/assets/88a1a52c-879f-4da1-8974-e5e42762659c)

![WhatsApp Image 2024-07-25 at 15 29 03](https://github.com/user-attachments/assets/5d27d8b0-0f72-4a35-b1e3-4bc3e5b59180)

**Comment by Mazaltov888** [comment] 2024-07-25 17:30
Good afternoon. Help me, please. I can't log in to my account. Haven't used the account in a year. Now I downloaded the app in Chrome. Entered the keys, password. I click on the activate button, but it won't click. You can see from the screenshots. Thank you very much in advance for your respect

![WhatsApp Image 2024-07-25 at 15 28 35](https://github.com/user-attachments/assets/95e59478-e48f-471b-bd77-53830db7d04f)

![WhatsApp Image 2024-07-25 at 15 29 30](https://github.com/user-attachments/assets/652a55d2-4126-4d16-8a5b-5ea6646ee529)

![WhatsApp Image 2024-07-25 at 15 29 15](https://github.com/user-attachments/assets/a33ed9f0-2ec3-4745-b9e2-07b7c2dd2bd0)

**Comment by F-OBrien** [comment] 2024-07-25 17:48
I tried it multiple times successfully. On one occasion clicking the "Add the account with the supplied seed" button didn't work but  just closed the popup and tried again, this time setting a single chain and it worked. I didn't check console for any errors.

All I can suggest to you is turn it off and back on again.

**Comment by maybe888** [comment] 2024-07-27 19:16
Team,
I have the same issue as the thread owner describes and shows on the screen shots:
"Entered the keys, password. I click on the activate button, but it won't click."
So, key is correct, password entered twice the orange bar appears, but it does not accept the click, just nothing happen.
I have the issue on Firefox extension. The issue came in probably with the new update between 21. - 26. Jul. 2024.

**Comment by F-OBrien** [comment] 2024-07-27 19:23
@maybe888 as this issue isn't easily reproducible it will help the developers if you report any errors from the popups console logs and/or service worker logs.

**Comment by maybe888** [comment] 2024-07-27 20:30
@F-OBrien well, that's the point: there is no error. It simply does not proceed with the reinsatallation of a given seed once a click on the orange button (after key and pw was added). The pictures above are perfectly describe the situation.
To get the orange button key and pw must be corret otherwise it come not up. 
Again, if there was an update between 21.-26. July 2024 the issue comes with this update.

**Comment by bee344** [comment] 2024-07-28 15:35
@maybe888 @Mazaltov888 let me see if I understood correctly. You are trying to import an account from a mnemonic seed, setting it to work on any chain, setting the name and password correctly and everything looks fine, but the button just doesn't  do anything? No errors, no warnings, neither in the console nor in the popup?

I have tried both on firefox and chrome and could not reproduce this.

Have you tried with the extension opened in a new window, not just as a popup? It would be useful to know if it's limited to the popup or to the extension as a whole

**Comment by maybe888** [comment] 2024-07-28 17:11
@bee344 Yes, you understand it right. I have the plug in running for years w/o an issue.
And yes, you have to have key & pw set right otherwise one don't get the orange bar.
I don't have Chrome but Firefox, earlier version and updated to latest version.
Not sure what you mean by "...openend in a new window"? Probably not, just the popup.
How to do new window? I think it is a browser exention...

**Comment by Tbaut** [comment] 2024-07-28 17:32
@maybe888 in the extension, at the top right, click on the settings icon (cogwheel), then it's the last menu entry "Open extension in new window"

**Comment by maybe888** [comment] 2024-07-28 18:20
@Tbaut @bee344 Ahh yes, I could use it in an extra window, Thank you!
But the same thing happened.
After key & pw were entered the orange bar comes up and once moving my mouse over the color slightly changes but it does not accept the click.
I started a second PC where the Polkadot.js is installed too. It doesn't work either. Clicking on the Pdot in the brower a window comes up with:    ...loading...
But nothing happens until +10 min.
Interesting that Mazaltov888 has the same thing but on Chrome extension.
What else can we try?

**Comment by bee344** [comment] 2024-07-28 19:31
@maybe888 about that " ...loading...", try closing the popup and opening it again, that usually fixes that instantly. Do you have any page open that uses the extension? Is it connected to anything?

**Comment by F-OBrien** [comment] 2024-07-28 20:18
> about that " ...loading...", try closing the popup and opening it again, that usually fixes that instantly. Do you have any page open that uses the extension? Is it connected to anything?

On firefox I've been able to replicate the "... loading ..." issue repeatably. Essentially I just wait for the background script to show as stopped in the dev tools about:debugging#/runtime/this-firefox before opening. It takes about 20-30 seconds of no activity for it to stop. Changing tabs, hovering over tabs etc can cause some message activity so I just stick on the dev tools page. 

![image](https://github.com/user-attachments/assets/f7677c19-2739-4174-aac3-39c39dbffde6)

(Note the background script wont stop if the inspect window is open as it keeps the script running.)
![image](https://github.com/user-attachments/assets/f41e2346-beda-4508-803b-3f0f23e1b7f0)

Then just try to open the extension. Video of the process attached for reference. I'm suspecting all of the cases where the extension fails to work are due to the background scripts stopping following the manifest V3 update. 

I was looking at the Subwallet extension and they have a heartbeat to keep the background page active. https://github.com/Koniverse/SubWallet-Extension/blob/master/packages/extension-koni/src/helper/HeartBeat.ts

https://github.com/user-attachments/assets/863d5aef-e01c-4875-ba42-9529e71f7111

**Comment by bee344** [comment] 2024-07-28 21:34
@F-OBrien I'm guessing the same as you and I'm currently trying things out to see how to stop that disconnect. Some very questionable decisions were made when defining manifest v3 and this seems to be caused by ine of them. The heartbeat is what I'm leaning towards, I'll try to get something ready for tomorrow. You've been a huge help so far, thanks.

**Comment by maybe888** [comment] 2024-07-29 19:01
@F-OBrien @bee344 Thanks a lot for your support! I'm very happy that you could reproduce the issue!
Hurray! 
During the week I'm away from my PC, being back on weekends only. Means, I can't try or check something during the week. 
Thanks again!

**Comment by Mazaltov888** [comment] 2024-07-31 15:14
Good evening. I still can't get in. Clicking on the button, nothing happens.
 I'm not a developer and I don't understand the video you. You posted on how to fix this error.
 Is there any crypto wallet that you can integrate keys into. From polkadot.js, 
 To open that wallet there .Help. Please solve this problem and I too will go on vacation for week .

**Comment by Tbaut** [comment] 2024-08-01 08:36
@Mazaltov888 there are other good wallets for users, such as Talisman, that you can import your keys into: https://www.talisman.xyz

Find the full list here: https://polkadot.network/ecosystem/wallets/

**Comment by TarikGul** [comment] 2024-08-09 16:03
@Mazaltov888 Can you please confirm this is fixed with the latest release that is out in the store?

**Comment by maybe888** [comment] 2024-08-10 17:50
@TarikGul Well, I tried today to install the plug in on Firefox again. But it leads to the same - absolute the same - result.
To be honest, I do not see an update, isn't still V 0.50.1 from Jul. 31st the latest version?

**Comment by TarikGul** [comment] 2024-08-10 23:26
@maybe888 Yea the new release is only on live Chrome - Firefox takes longer to get approved for the store and should be in some time this week. Sorry I should have been more clear - I just noticed @Mazaltov888 was using chrome above.

**Comment by maybe888** [comment] 2024-08-11 14:50
@TarikGul No no, to be Sorry is on my side to interfere, you have been clear. This is excellent news that Firefox update might come in roughly within a week. I'm curious for next weekend... Thank You!

**Comment by maybe888** [comment] 2024-08-31 19:39
@TarikGul Just to confirm from my side that the new release works on Firefox too. Thanks a lot!

**Closed** 2024-09-01 11:02 UTC
