### ISSUE TITLE
Don't ask confirmation if extrinsic costs less than X tokens

### ISSUE THREAD

**Issue by siman** [polkadot-js/extension#276] opened 2020-03-17 21:38 UTC
It would be very helpful for UX of some dapps to not ask a current user for confirmation if extrinsic costs less than X tokens and/or until the daily limit of tokens spent.

## Example

If there is an extrinsic `upvote_comment` and it has a small price (0.1 cents) then it would help to have an option or per-chain setting in Extension where a it's specified: "Don't ask confirmation if extrinsic costs less than X tokens". 

## Additional guard

As an additional guard, there could be a check that total spendings per day do not exceed Y amount of tokens. Once you spent more than Y amount of tokens - then a current user should be asked to reconfirm whether he/she is ok to continue sending such kind of txs without asking a confirmation to sign them.

**Comment by jacogr** [comment] 2020-03-24 10:44
As per #275, this is probably not something that will be done here, or rather not without additional complexity that needs to be managed.

**Comment by jacogr** [comment] 2020-09-09 12:56
I'm closing this one as "wontfix". The issue is to do this it needs to understand all extrinsics (to determine cost based on the fields) and have some idea of the on-chain fees. This is simply not practical, nor is the extension connected to any network. 

The "per-extrinsic" idea (as per #275) can rather be done practically and encompasses this specifically to the user's wishes (although that obviously has it's own set of issues around management per chain and per set).

**Closed by jacogr** 2020-09-09 12:56 UTC
Labels: <unconfirmed>

**Comment by siman** [comment] 2020-09-09 13:02
Makes sense. It's really tricky to get an extrinsic cost in advance :(
