### ISSUE TITLE
help asap i am in the auctions need access to my wallet

### ISSUE THREAD

**Issue by TerraLunatic** [polkadot-js/extension#916] opened 2021-12-10 05:54 UTC
<img width="1512" alt="Screen Shot 2021-12-09 at 11 50 29 PM" src="https://user-images.githubusercontent.com/95900028/145524315-e93e2d65-1ed6-47a4-8114-ad5425105fce.png">
 
this is what it says on firefox when you enter your seed phrase

**Comment by jacogr** [comment] 2021-12-10 07:57
Duplicate of #915, same user.

**Closed by jacogr** 2021-12-10 07:57 UTC
Labels: <duplicate>
