### ISSUE TITLE
Hardware Wallet Integration

### ISSUE THREAD

**Issue by chrishobcroft** [polkadot-js/extension#143] opened 2019-09-10 00:27 UTC
I want to be able to sign transactions via my Trezor.

**Comment by jacogr** [comment] 2019-09-10 06:07
As would I... 

HW wallet integration will certainly be integrated as soon as there is actually hardware support for Substrate/Polkadot transaction payloads, there are a number of teams that is working on this for a variety of devices. Until that is available, nothing we can do but wait.

The actual W3F tracking issue for proposals is here - https://github.com/w3f/Web3-collaboration/issues/14

**Comment by jacogr** [comment] 2019-09-10 06:09
Marking it "unconfirmed" since there is really no action that can be taken at this point in time. (Actually should probably be closed and replaced with specific HW wallet tickets as soon as they can be integrated)

**Comment by Tbaut** [comment] 2020-12-11 11:34
closing since this is too general and only ledger support Polkadot/Kusama so far, and it's logged.

**Closed by Tbaut** 2020-12-11 11:34 UTC
Labels: <unconfirmed>, @extension
