### ISSUE TITLE
Display full transaction hex

### ISSUE THREAD

**Issue by xlc** [polkadot-js/extension#1069] opened 2022-05-19 03:43 UTC
I can see why https://github.com/polkadot-js/extension/issues/1035 is not going to happen. A quick workaround is that have the extension display the transaction hex so that I can copy it into polkadot apps and use the Decode page to dispatch it using Proxy / Multisig.

A nicer addition feature will be allow me add any arbitrary account so I can add Proxy / Multisig account (or Gav's account) and have the dApp display all the relevant information of this account. Of course the signing is not going to work but if can still display the tx information and the hex so I can use polkadot apps to dispatch it (or send it to the real owner).

**Comment by xlc** [comment] 2022-06-09 07:16
@jacogr do I really need to write a bot to counter your bot to close my issue?

**Comment by jacogr** [comment] 2022-06-09 07:53
Looked at this one this morning again when it was flagged. This one is unlikely to be done at all - the extension is to be simple, without trying to feed through extra info and/or display the underlying tech info. The extension is only a signer. This is one suggestion to get around the issues, but it is not something that ends up as a solution.

(The one valuable thing above however is having the extension act as an [address book](https://github.com/polkadot-js/extension/issues/646), something that is in the queue - so at best, this is a duplicate of that requirement)

**Comment by xlc** [comment] 2022-06-09 08:22
All I need is display the transaction hex value so that I can copy it, it should be trivial?

**Comment by jacogr** [comment] 2022-06-10 08:08
None of this solves you issue - in your case, the transaction hex won't help at all since you can see the stuff, but you cannot tweak it into something wrapped with a proxy in the apps UI. (And even if we had address book functionality, that doesn't allow submission - they are not addresses)

If you have the hex and the apps UI can submit it, it means you can submit it from the extension as well. Anything that needs to be wrapped or re-created is a non-starter. You need to fill in all the details, which you have anyway in the extension.

So I understand _what_ you want to solve, but this is not the way.

As for security - let's not go there. I get consistent bitching from people not updating metadata and then seeing "secure" hex.

**Comment by jacogr** [comment] 2022-06-10 08:17
EDIT: And yes, I _also_ despite sounding grumpy want to solve the proxy/multisig/sub/etc. submission. We need the right way to do so, adding moving parts with 2 different interactions as you want here is not the way.

**Comment by xlc** [comment] 2022-06-10 21:42
Ok. You are more qualified to determine what’s the right solution but I also want to express my frustration that I see zero roadmap from solving this one of the biggest UX hurdle in the ecosystem. I talked with every single wallet team and yet nothing valuable coming out of it. 

This maybe a poor workaround but I would need to see what’s the right solution first to accept the fact this workaround should not be implemented.

**Comment by jacogr** [comment] 2022-06-12 12:52
I would suggest that your "every single wallet team" logs issues and stops speaking in private. If it is not visible, I can't smell enhancements. I can also make accusations without backing data - it is really simple complaining instead of solving.

If you have real specific ways of solving the specific issue which also affects the "single developer that cannot focus on this full-time", I'm all ears.

As of now, this won't go in, but as above - happy for real solutions, this one is not it. It won't work since there is no infrastructure to actually make this a possibility, makes it more complex, increase the number of tickets, etc.

**Closed by jacogr** 2022-06-12 12:52 UTC
