### ISSUE TITLE
Account no longer injected after rejecting extension access once

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/extension#404] opened 2020-08-11 19:04 UTC
On polkadot (albeit it should be irrelevant): I rejected polkadot-js extension access once when the pop up shows up, and now I can no longer inject the account. The pop up simple does not show up. The UI shows this: 

> One of more extensions has been detected in your browser, however no accounts has been injected.
> Ensure that the extension has accounts, some accounts are visible globally and available for this chain and that you gave the application permission to access accounts from the extension to use them.

And I can ensure that the extension has the accounts, and that they are visible globally.

**Comment by kianenigma** [comment] 2020-08-11 19:05
Browser: brave.

**Comment by jacogr** [comment] 2020-08-11 20:01
Duplicate of https://github.com/polkadot-js/extension/issues/85

Switch the extension on/off to re-prompt.

**Closed** 2020-08-14 20:25 UTC
Labels: <duplicate>, <question>
