### ISSUE TITLE
Can not create new derive account

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/extension#633] opened 2021-01-26 23:27 UTC
I tried to create a new derive account //2 but it ended up with no account created, and the name I gave to the new account was given to account //0 .

extension version 0.36.1, browser: chrome Version 88.0.4324.96 (Official Build) (x86_64)

<img width="520" alt="Screen Shot 2021-01-27 at 12 20 11 PM" src="https://user-images.githubusercontent.com/39037239/105919621-dd5cab00-609a-11eb-8fec-cc921d95eb86.png">

<img width="552" alt="Screen Shot 2021-01-27 at 12 21 58 PM" src="https://user-images.githubusercontent.com/39037239/105919640-e2b9f580-609a-11eb-8711-e0052d3dd1ce.png">

<img width="544" alt="Screen Shot 2021-01-27 at 12 22 52 PM" src="https://user-images.githubusercontent.com/39037239/105919659-e9e10380-609a-11eb-9b34-3565874dcd0f.png">

<img width="523" alt="Screen Shot 2021-01-27 at 12 23 33 PM" src="https://user-images.githubusercontent.com/39037239/105919672-ee0d2100-609a-11eb-9280-1c09959106d6.png">

**Comment by Tbaut** [comment] 2021-01-27 09:25
Thanks for reporting. Despite trying hard, I cannot reproduce what you explain.
> ![image](https://user-images.githubusercontent.com/33178835/105968895-eee88780-6087-11eb-9dfe-647bb81d7c97.png)

^ This screenshot shows that the derived account, is the same as your "noa1 //0" account in your first scree. This means that for some reason, the derivation path must have been `//0`, you have then overridden the original name for this same account.

Here is a flow where I derive the same account and override the name
https://user-images.githubusercontent.com/33178835/105969802-f0667f80-6088-11eb-96bb-38f6f5478828.mp4

I really do no understand how it is possible to end up in the situation you describe. Are you able to reproduce this problem consistently?

This is what happens when I derive an account, that has already one //0 derivation child.
https://user-images.githubusercontent.com/33178835/105970602-d8433000-6089-11eb-9d11-f53ffac3d3d4.mp4

**Comment by ianhe8x** [comment] 2021-01-27 19:28
I can reproduce it, only this specific account I can not create derive account from

**Comment by Tbaut** [comment] 2021-01-27 19:34
Thanks for the follow up. I will try to reproduce with other types of account tomorrow. 

In the mean time, do you happen to know what crypto this account uses (sr25519 or ed25519?). Did you import it using a Json file?

**Comment by jacogr** [comment] 2021-01-27 19:35
The only one where derivation does not work (it is ignored completely is “Ethereum” accounts. For the rest it should derive)

**Comment by ianhe8x** [comment] 2021-01-28 02:59
It took me a while but I found the place~

To reproduce it, 
1. use the right corner menu action: `Derive from an account`
2. the default account must be an account without derived
3. switch to the account that has been derived
4. continue and you shall see it

The code I have traced to is here https://github.com/polkadot-js/extension/blob/9046da1ee5057013465516f33163295d0b9a961e/packages/extension-ui/src/Popup/Derive/SelectParent.tsx#L31

The ui shows the next suri for new account is from `defaultPath`, but the actual value passed to background is from `suriPath` which hasn't been updated after switching parent account.

**Comment by Tbaut** [comment] 2021-01-28 10:32
Thanks a lot for the additional details and your research, the culprit was indeed the fact that if you changed the parent, the default derivation path didn't change, if not noticed, this could lead to overriding an already existing account.

This will be fixed in the next release :pray: .

**Closed** 2021-01-28 12:18 UTC
Labels: -size-s, @extension-ui, [bug]
