### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 28657** [polkadot-js/extension#539] opened 2020-11-23 10:42 UTC
https://gitcoin.co/townsquare?tab=activity:442852

**Comment by jacogr** [comment] 2020-11-23 11:10
Going to close this, please provide informative details - really prefer not clicking through on links, they could be anything.

**Comment by Tbaut** [comment] 2020-11-23 11:11
Quoting what you wrote elsewhere:
> I don't know where to send the bug, so I'm sending it here
https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd
When you create a wallet and try to save a key or seed phrase, you need to open a notebook.
The problem is that if you minimize the browser the key will change again. 

Closing as this is a duplicate from https://github.com/polkadot-js/extension/issues/400
Please follow/comment in this issue.

**Closed** 2020-11-23 11:10 UTC
